# Generated by Django 2.2.12 on 2020-11-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasDetails',
            fields=[
                ('gasId', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('gas', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
